### ISSUE TITLE
脚本生成trojan类型url拼写错误

### ISSUE THREAD

**Issue by jaychoubaby** [233boy/sing-box#1]
------------- 链接 (URL) -------------
trojan://********************************?type=tcp&security=tls&allowlnsecure=1#233boy-trojan-************

其中allowlnsecure  w后面应该是大写的 i   ，而不是小写的L，换个字体就可以明显的看出来

**Comment by jaychoubaby** [comment]
![image](https://github.com/233boy/sing-box/assets/26641387/4f5e34f6-adff-4420-8103-0523e20c6687)

**Comment by 233boy** [comment]
@jaychoubaby 

45b0991

感谢提醒，修复了，使用 `sb up sh` 更新即可
