### ISSUE TITLE
Caddy停止

### ISSUE THREAD

**Issue by WangHan2014** [233boy/sing-box#10]
总是会在使用一段时间后Caddy服务就挂了

Aug 27 09:01:27 systemd[1]: caddy.service: Main process exited, code=killed, status=9/KILL
Aug 27 09:01:27 systemd[1]: caddy.service: Failed with result 'signal'.
Aug 27 09:01:27 systemd[1]: caddy.service: Consumed 2min 56.492s CPU time.

使用的是Trojan

警告! Caddy 当前处于停止状态.

**Comment by WangHan2014** [comment]
发现了一个停止原因：OOM
VPS有约450M可用内存，看来还是配置低了。。。。

**Comment by 233boy** [comment]
如果是真实的 450M 肯定是够用的，你哪家的VPS？你这个是母机起售严重了

**Comment by WangHan2014** [comment]
> 如果是真实的 450M 肯定是够用的，你哪家的VPS？你这个是母机超售严重了

CloudCone $9.9/Year 这个之前用了好几年，之前用的V2ray和SS没啥问题，前段时间刚换成sing-box

**Comment by WangHan2014** [comment]
加大了Swap分区，目前为止还没复现
