### ISSUE TITLE
【功能请求】安装时支持通过自定义反向代理地址连接 Github

### ISSUE THREAD

**Issue by NierCaraLynn** [233boy/sing-box#13]
我在国内服务器上尝试搭建海外回国节点，但在安装过程中遇到了网络问题。由于中国大陆访问 GitHub 会受到 GFW 的干扰，建议在安装时提供一个选项，允许用户通过自定义反向代理地址来连接 GitHub 仓库，以便顺利完成安装 >_<

**Comment by 233boy** [comment]
@NierCaraLynn 不要啊求求你，不要国内装我脚本（你可以装别人的

**Comment by NierCaraLynn** [comment]
啊？好的

我只是在新加坡留学时和哥们当作游戏加速器用，大佬要介意的话我就不用了（
