### ISSUE TITLE
套cdn，只有ws能成功

### ISSUE THREAD

**Issue by Facico** [233boy/sing-box#16]
由于VPS的IP已经被封了，需要套CDN。
然后只有trojan/vless/vmess + ws能配置成功，其他的都失败了。 ps：据说ws会泄露go客户端的tls指纹，想换一下其他的协议

想问一下有没有相似的情况，或者有没有解决办法

**Comment by Facico** [comment]
grpc在cloudfare是可以在network打开的。想问一下h2这种要咋办。
然后如果要换成reality的话，是得把cdn的tls给关掉吗

**Comment by 233boy** [comment]
> grpc在cloudfare是可以在network打开的。想问一下h2这种要咋办。 然后如果要换成reality的话，是得把cdn的tls给关掉吗

@Facico 被封了也用不了 reality 啊，用 ws tls 套CF 就行了

**Comment by Facico** [comment]
@233boy 嗯嗯。之前我ws tls套CF的方案用了好几年，最近发现出现疑似SNI干扰，打算换个方案。
我还是先用grpc试试
